name: Daily Python Script Execution

on: push

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run 01_generate_ticker_data.py
      run: python modules/01_generate_ticker_data.py

    - name: Run 02_generate_gme_financials.py
      run: python modules/02_generate_gme_financials.py

    - name: Commit and push changes
      run: |
        git config --local user.email "keeney.archadia@gmail.com"
        git config --local user.name "saint-vampirdus"
        git remote set-url origin https://${{ secrets.ACTIONS_TOKEN }}@github.com/saint-vampirdus/GMERICA.git
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated update: $(date '+%Y-%m-%d %H:%M:%S')"
        git push